
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author osmar
 */
public class ModificarC extends javax.swing.JPanel {

    Carga_y_Asignacion CyA = new Carga_y_Asignacion();
    
    public String BaseP = Conexion.Base;
    public String PP1 = "";
    public String PP2 = "";
    public String PP3 = "";
    public String PP4 = "";
    public static double Cantidad1 = 0;
        
    public static String formattedDate = "";
    public static int TCP = 0;
    
    
    
    public ModificarC() {
        initComponents();
        
        Llenar();
        
        JTextField dateTextField = (JTextField) CalendarModSal.getDateEditor().getUiComponent();
        dateTextField.setEnabled(false);
        dateTextField.setBackground(new java.awt.Color(240,240,240));
        dateTextField.setForeground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIDMod = new javax.swing.JTextField();
        txtProdMod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantMod = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtFechMod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTurnMod = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CheckProd = new javax.swing.JCheckBox();
        CheckFecha = new javax.swing.JCheckBox();
        CheckTurn = new javax.swing.JCheckBox();
        CheckCant = new javax.swing.JCheckBox();
        txtFiltProdModF = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        CmbUser = new javax.swing.JComboBox<>();
        CalendarModSal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "Modificar Salida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(255, 102, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        txtIDMod.setEditable(false);
        txtIDMod.setBackground(new java.awt.Color(255, 255, 255));
        txtIDMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIDMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        txtIDMod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIDMod.setEnabled(false);
        txtIDMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDModMouseClicked(evt);
            }
        });
        txtIDMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDModActionPerformed(evt);
            }
        });

        txtProdMod.setEditable(false);
        txtProdMod.setBackground(new java.awt.Color(255, 255, 255));
        txtProdMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProdMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProdMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtProdMod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProdMod.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Producto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad");

        txtCantMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("MODIFICAR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtFechMod.setEditable(false);
        txtFechMod.setBackground(new java.awt.Color(255, 255, 255));
        txtFechMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtFechMod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechMod.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Turno");

        txtTurnMod.setEditable(false);
        txtTurnMod.setBackground(new java.awt.Color(255, 255, 255));
        txtTurnMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTurnMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTurnMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtTurnMod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTurnMod.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "FiltroSalida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 102, 0))); // NOI18N

        CheckProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckProd.setForeground(new java.awt.Color(255, 102, 0));
        CheckProd.setText("PRODUCTO");
        CheckProd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckProd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckProdMouseClicked(evt);
            }
        });

        CheckFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckFecha.setForeground(new java.awt.Color(255, 102, 0));
        CheckFecha.setText("FECHA");
        CheckFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckFecha.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckFechaMouseClicked(evt);
            }
        });

        CheckTurn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckTurn.setForeground(new java.awt.Color(255, 102, 0));
        CheckTurn.setText("TURNO");
        CheckTurn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckTurn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckTurnMouseClicked(evt);
            }
        });
        CheckTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTurnActionPerformed(evt);
            }
        });

        CheckCant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckCant.setForeground(new java.awt.Color(255, 102, 0));
        CheckCant.setText("CANTIDAD");
        CheckCant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckCant.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckCant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckCantMouseClicked(evt);
            }
        });

        txtFiltProdModF.setEditable(false);
        txtFiltProdModF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFiltProdModF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFiltProdModF.setText("Buscar");
        txtFiltProdModF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        txtFiltProdModF.setEnabled(false);
        txtFiltProdModF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltProdModFMouseClicked(evt);
            }
        });
        txtFiltProdModF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltProdModFActionPerformed(evt);
            }
        });

        txtCant.setEditable(false);
        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCant.setForeground(new java.awt.Color(204, 204, 204));
        txtCant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCant.setText("Especificar");
        txtCant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        txtCant.setEnabled(false);
        txtCant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantMouseClicked(evt);
            }
        });

        CmbUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CmbUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        CmbUser.setEnabled(false);
        CmbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbUserMouseClicked(evt);
            }
        });

        CalendarModSal.setBackground(new java.awt.Color(255, 255, 255));
        CalendarModSal.setDateFormatString("dd/MM/yyyy");
        CalendarModSal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CalendarModSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarModSalMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("FILTRAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CheckTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckCant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCant, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiltProdModF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmbUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CalendarModSal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltProdModF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(CalendarModSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantMod, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechMod, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTurnMod)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIDMod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdMod))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechMod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtCantMod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtTurnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDModActionPerformed
        
    }//GEN-LAST:event_txtIDModActionPerformed

    private void txtIDModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDModMouseClicked
        FiltroID FIDo = new FiltroID();
        FIDo.setVisible(true);
    }//GEN-LAST:event_txtIDModMouseClicked

    private void txtFiltProdModFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltProdModFMouseClicked
        
        CheckProd.setSelected(true);
        
        txtFiltProdModF.setText("");
        txtFiltProdModF.setBackground(Color.WHITE);
        txtFiltProdModF.setForeground(new java.awt.Color(0,0,0));
        
        BuscarProducto BP = new BuscarProducto();
        BP.setVisible(true);
        BP.Frame = 2; 

    }//GEN-LAST:event_txtFiltProdModFMouseClicked

    private void txtFiltProdModFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltProdModFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltProdModFActionPerformed

    private void CalendarModSalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalendarModSalMouseClicked
      
    }//GEN-LAST:event_CalendarModSalMouseClicked

    private void CheckProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckProdMouseClicked
        
        if (CheckProd.isSelected() == true){
            txtFiltProdModF.setText("");
            txtFiltProdModF.setBackground(Color.WHITE);
            txtFiltProdModF.setForeground(new java.awt.Color(0,0,0));
            
            BuscarProducto BP = new BuscarProducto();
            BP.setVisible(true);
            BP.Frame = 2; 
        }else{
            txtFiltProdModF.setText("Buscar");
            txtFiltProdModF.setBackground(new java.awt.Color(240,240,240));
        }
        
    }//GEN-LAST:event_CheckProdMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!txtFiltProdModF.getText().equals("")){
            if (!txtCant.getText().equals("")){
                if (CmbUser.getSelectedIndex() != -1){
                    LlamarFecha();
                    ConsDatosSalidaP();
                }else{
                    if (CheckTurn.isSelected() == true){
                        JOptionPane.showMessageDialog(null, "Favor de SELECCIONAR un USUARIO o DESACTIVAR el filtro", "Advertencia", JOptionPane.ERROR_MESSAGE);
                    }else{
                        LlamarFecha();
                        ConsDatosSalidaP();
                    }                   
                }
            }else{
                JOptionPane.showMessageDialog(null, "Favor de INDICAR una CANTIDAD o DESACTIVAR el filtro", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Favor de SELECCIONAR un PRODUCTO o DESACTIVAR el filtro", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CheckTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckTurnMouseClicked
        
        if (CheckTurn.isSelected() == true){
            CmbUser.setEnabled(true);
            CmbUser.setSelectedIndex(0);
        }else{
            CmbUser.setEnabled(false);
            CmbUser.setSelectedIndex(-1);
        }
        
    }//GEN-LAST:event_CheckTurnMouseClicked

    private void CmbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbUserMouseClicked
        
        CheckTurn.setSelected(true);
        CmbUser.setEnabled(true);
        CmbUser.setSelectedIndex(0);
        
    }//GEN-LAST:event_CmbUserMouseClicked

    private void txtCantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantMouseClicked
        
        CheckCant.setSelected(true);
        
        txtCant.setEditable(true);
        txtCant.setEnabled(true);
        txtCant.setText("");
        txtCant.setBackground(Color.WHITE);
        txtCant.setForeground(new java.awt.Color(0,0,0));
        
    }//GEN-LAST:event_txtCantMouseClicked

    private void CheckCantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckCantMouseClicked
        
        if (CheckCant.isSelected() == true){
            txtCant.setText("");
            txtCant.setBackground(Color.WHITE);
            txtCant.setForeground(new java.awt.Color(0,0,0));
            txtCant.setEnabled(true);
            txtCant.setEditable(true);
        }else{
            txtCant.setText("Especificar");
            txtCant.setBackground(new java.awt.Color(240,240,240));
            txtCant.setForeground(new java.awt.Color(140,140,140));
            
        }
        
    }//GEN-LAST:event_CheckCantMouseClicked

    private void CheckFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckFechaMouseClicked
        
        JTextField dateTextField = (JTextField) CalendarModSal.getDateEditor().getUiComponent();
        
        LocalDate now = LocalDate.now();
                
        DateTimeFormatter formOneM = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        
        Date d = new Date(now.format(formOneM));
        
        System.out.println(d);
        
        if (CheckFecha.isSelected() == true){
            dateTextField.setBackground(new java.awt.Color(255,255,255));
            dateTextField.setForeground(new java.awt.Color(0,0,0));
            CalendarModSal.setDate(d);
        }else{
            dateTextField.setBackground(new java.awt.Color(240,240,240));
            dateTextField.setForeground(new java.awt.Color(255,255,255));
            dateTextField.setText("");
        }
        
    }//GEN-LAST:event_CheckFechaMouseClicked

    private void CheckTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTurnActionPerformed
 
    }//GEN-LAST:event_CheckTurnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        if(txtIDMod.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Para poder MODIFICAR un producto PRIMERO tienes que SELECCIONARLO", "ADVERTENCIA", JOptionPane.OK_OPTION);
        }else{
            if (esDouble(txtCantMod.getText())){
                int lo = JOptionPane.showConfirmDialog(null, "¿Estas seguro de querer cambiar la cantidad de " + Cantidad1 + " a " + txtCantMod.getText() + "?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        
                if (lo == JOptionPane.OK_OPTION) {
                    UpDat();
                    UpCan();
                    NuevaC NC = new NuevaC();
                    NC.ConsDatosSalida();
                    Limp();
                } else {
                    System.out.println("El usuario presionó Cancel o cerró el diálogo");
                }  
            }else{
                JOptionPane.showMessageDialog(null, "Favor de ingresar un valor valido", "Advertencia", JOptionPane.ERROR_MESSAGE);
            } 
            
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

public void ConsDatosSalidaP() {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        modelo.addColumn("ID");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Hora");

        TablaG.TbBusqueda.setModel(modelo);
        TablaG.TbBusqueda.setFocusable(true);
        TablaG.TbBusqueda.setRowSelectionAllowed(true);
        
        //Reinicio de Variables Globales (PP1 - PP2 - PP3 - PP4)
        PP1 = "";
        PP2 = "";
        PP3 = "";
        PP4 = "";
        TCP = 0;
        
        System.out.println(PP1);
        System.out.println(PP2);
        System.out.println(PP3);
        System.out.println(PP4);
        System.out.println(TCP);

        String sql;
        ResultSet rs;
        Statement st;

        String Fecha = CyA.GlobFecha;
        String Usuario = Principal.Nombre;
        String Base = ""; 
        
        String[] datos = new String[4];
        
        if (CheckFecha.isSelected() == true && CheckTurn.isSelected() == true){
            Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where ";
        }else{
            if (CheckFecha.isSelected() == true){
                TCP++;
                Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Usuario = '" + Usuario + "'";
            }else{
                if (CheckTurn.isSelected() == true){
                    TCP++;
                    Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Fecha = '" + Fecha + "'";
                }else{
                    TCP++;
                   Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Usuario = '" + Usuario + "' and Salida.Fecha = '" + Fecha + "'"; 
                }
            }
        }
                   
        //if que me comprueba el estado del check PRODUCTO
        if (TCP >= 1){
            if (CheckProd.isSelected() == true){
                PP1 = " and Salida.Producto = '" + txtFiltProdModF.getText() + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Producto");
            }
        }else{
            if (CheckProd.isSelected() == true){
                PP1 = "Salida.Producto = '" + txtFiltProdModF.getText() + "'";
                TCP++;
            }else{
                PP1 = "";
                System.out.println("No se selecciono el filtro de Producto");
            }
        }
        
        //if que me comprueba el estado del check FECHA
        if (TCP >= 1){
            if (CheckFecha.isSelected() == true){
                PP2 = " and Salida.Fecha = '" + formattedDate + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Fecha");
            }
        }else{
            if (CheckFecha.isSelected() == true){
                PP2 = "Salida.Fecha = '" + formattedDate + "'";
                TCP++;
            }else{
                PP2 = "";
                System.out.println("No se selecciono el filtro de Fecha");
            }
        }
        
        //if que me comprueba el estado del check CANTIDAD
        if (TCP >= 1){
            if (CheckCant.isSelected() == true){
                PP3 = " and Salida.Cantidad = '" + txtCant.getText() + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Cantidad");
            }
        }else{
            if (CheckCant.isSelected() == true){
                PP3 = "Salida.Cantidad = '" + txtCant.getText() + "'";
                TCP++;
            }else{
                PP3 = "";
                System.out.println("No se selecciono el filtro de Cantidad");
            }
        }
        
        //if que me comrueba el estado del check TURNO
        if (TCP >= 1){
            if (CheckTurn.isSelected() == true){
                PP4 = " and Salida.Usuario = '" + CmbUser.getSelectedItem().toString() + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Turno");
            }
        }else{
            if (CheckTurn.isSelected() == true){
                PP4 = "Salida.Usuario = '" + CmbUser.getSelectedItem().toString() + "'";
                TCP++;
            }else{
                PP4 = "";
                System.out.println("No se selecciono el filtro de Turno");
            }
        }
        
        sql = Base + PP1 + PP2 + PP3 + PP4 + ";";
        System.out.println(sql);
        
        try {
            
            st = cn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                double valorCant = Double.parseDouble(rs.getString(3));
                System.out.println(valorCant);
                DecimalFormat df = new DecimalFormat("0.000");
                datos[2] = df.format(valorCant) + " Kg";
                datos[3] = rs.getString(4);
                
                
                modelo.addRow(datos);
            }
            TablaG.TbBusqueda.setModel(modelo);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(NuevaC.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        Principal.ajustarAnchoColumnas(TablaG.TbBusqueda);
        Principal.centrarColumnas(TablaG.TbBusqueda);
        
        TableColumn primeraCol = TablaG.TbBusqueda.getColumnModel().getColumn(0);
        primeraCol.setHeaderRenderer(new FormHeaderCenter()); 
        
        TableColumn SegCol = TablaG.TbBusqueda.getColumnModel().getColumn(1);
        SegCol.setHeaderRenderer(new FormHeaderLeft());
        
        TableColumn terceraCol = TablaG.TbBusqueda.getColumnModel().getColumn(2);
        terceraCol.setHeaderRenderer(new FormHeaderCenter());
        
        TableColumn cuartaCol = TablaG.TbBusqueda.getColumnModel().getColumn(3);
        cuartaCol.setHeaderRenderer(new FormHeaderCenter());
    }

public void LlamarFecha() {
    Date selectedDate = CalendarModSal.getDate();   
        
        if (selectedDate != null) {
           SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
           formattedDate = dateFormat.format(selectedDate);
           System.out.println("Fecha seleccionada: " + formattedDate); 
        }else{
            System.out.println("No se selecciono fecha");
        }
}

private void Llenar () {
    String sql = "select Nombre from " + BaseP + ".Usuario;";
    ResultSet rs;
    Statement st;
        try {
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            
            while (rs.next()) {
                String Usuario = rs.getString(1);
                CmbUser.addItem(Usuario);
            }
            rs.close();
        }catch (SQLException ex){
            Logger.getLogger(ModificarC.class.getName()).log(Level.SEVERE, null, ex);
        }
    CmbUser.setSelectedIndex(-1);
}

public void UpDat() {              
        try {
            PreparedStatement pst = cn.prepareStatement("update " + BaseP + ".Salida"                    
                    + " set Cantidad = ?"
                    + "where idSalida = ?");
            
            pst.setDouble(1, Double.parseDouble(txtCantMod.getText()));
            pst.setInt(2, Integer.parseInt(txtIDMod.getText()));

            pst.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(ModificarC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public static void Limp(){
    txtIDMod.setText("");
    txtProdMod.setText("");
    txtCantMod.setText("");
    txtFechMod.setText("");
    txtTurnMod.setText("");
}

private void UpCan(){
    
    double CantT = 0;
    double CanPreUp = 0;
    double CanUp = 0;
    
    String sql0 = "select cantidad from " + BaseP + ".Producto where Producto = ?";
    String sql1 = "update " + BaseP + ".producto set cantidad = ? where producto = ?";
    
    try(PreparedStatement pst0 = cn.prepareStatement(sql0)){
        pst0.setString(1, txtProdMod.getText());
        try(ResultSet rs0 = pst0.executeQuery()){
            while(rs0.next()){
                CantT += rs0.getDouble(1);
            }
        }
        
        CanPreUp = CantT - Cantidad1;
        CanUp = CanPreUp + Double.parseDouble(txtCantMod.getText());
        
        try(PreparedStatement pst1 = cn.prepareStatement(sql1)){
            pst1.setDouble(1, CanUp);
            pst1.setString(2, txtProdMod.getText());
            pst1.executeUpdate();
        }
    }catch(SQLException ex){
        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, "Error al calcular la cantidad total", ex);
        return; 
    }
}

public boolean esDouble(String str) {
    if (str == null || str.isEmpty()) {
        return false; // Una cadena nula o vacía no es un double
    }
    try {
        Double.parseDouble(str);
        return true; // Si la conversión es exitosa, la cadena es un double
    } catch (NumberFormatException e) {
        return false; // Si ocurre una excepción, la cadena no es un double
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser CalendarModSal;
    private javax.swing.JCheckBox CheckCant;
    private javax.swing.JCheckBox CheckFecha;
    private javax.swing.JCheckBox CheckProd;
    private javax.swing.JCheckBox CheckTurn;
    public static javax.swing.JComboBox<String> CmbUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtCant;
    public static javax.swing.JTextField txtCantMod;
    public static javax.swing.JTextField txtFechMod;
    public static javax.swing.JTextField txtFiltProdModF;
    public static javax.swing.JTextField txtIDMod;
    public static javax.swing.JTextField txtProdMod;
    public static javax.swing.JTextField txtTurnMod;
    // End of variables declaration//GEN-END:variables
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
}
