
import java.awt.BorderLayout;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author osmar
 */
public class NuevaC extends javax.swing.JPanel {
    
    Carga_y_Asignacion CyA = new Carga_y_Asignacion();
    
    
    public String BaseP = Conexion.Base;
    //" + BaseP + "
    
    public NuevaC() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtIDNuevaSalida = new javax.swing.JTextField();
        txtProdNueva = new javax.swing.JTextField();
        BtnBuscarProdNuevaSalida = new javax.swing.JButton();
        txtCantNueva = new javax.swing.JTextField();
        BtnConfNueva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LBIconHelp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nueva Salida");

        setBackground(new java.awt.Color(255, 255, 255));

        txtIDNuevaSalida.setEditable(false);
        txtIDNuevaSalida.setBackground(new java.awt.Color(255, 255, 255));
        txtIDNuevaSalida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIDNuevaSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIDNuevaSalida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtIDNuevaSalida.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIDNuevaSalida.setEnabled(false);
        txtIDNuevaSalida.setFocusable(false);

        txtProdNueva.setEditable(false);
        txtProdNueva.setBackground(new java.awt.Color(255, 255, 255));
        txtProdNueva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProdNueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProdNueva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        txtProdNueva.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProdNueva.setEnabled(false);
        txtProdNueva.setFocusable(false);

        BtnBuscarProdNuevaSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnBuscarProdNuevaSalida.setForeground(new java.awt.Color(255, 102, 0));
        BtnBuscarProdNuevaSalida.setText("BUSCAR");
        BtnBuscarProdNuevaSalida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        BtnBuscarProdNuevaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarProdNuevaSalidaActionPerformed(evt);
            }
        });

        txtCantNueva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCantNueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantNueva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        BtnConfNueva.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnConfNueva.setForeground(new java.awt.Color(255, 102, 0));
        BtnConfNueva.setText("AGREGAR");
        BtnConfNueva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        BtnConfNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfNuevaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Producto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad:");

        LBIconHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBIconHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagen1.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nueva Salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBuscarProdNuevaSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDNuevaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdNueva)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnConfNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBIconHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBIconHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDNuevaSalida)
                    .addComponent(txtProdNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBuscarProdNuevaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnConfNueva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantNueva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfNuevaActionPerformed
        if (!txtIDNuevaSalida.getText().equals("")){ 
                
            String ID = txtIDNuevaSalida.getText();
            System.out.println(ID);
            
            String Producto = txtProdNueva.getText();
            System.out.println(Producto);
                
            if(!txtCantNueva.getText().equals("")){
                if(esDouble(txtCantNueva.getText())){

                String Cant = txtCantNueva.getText();
                System.out.println(Cant);
                
                ConfirmarSalida CS = new ConfirmarSalida();
                CS.setVisible(true);
                
                CS.txtIDDatSal.setText(ID);
                CS.txtProdDatSal.setText(Producto);
                CS.txtCanDatSal.setText(Cant);
                
                CS.txtFechaDatSal.setText(Carga_y_Asignacion.GlobFecha);
                CS.txtHrsDatSal.setText(Carga_y_Asignacion.GlobHora);
                CS.txtTurnDatSal.setText(Principal.Nombre);
                
                this.removeAll();
                this.revalidate();
                this.repaint();
                }else{
                    JOptionPane.showMessageDialog(null, "Favor de ingresar un valor valido", "Advertencia", JOptionPane.ERROR_MESSAGE);
                }   
            }else {
              JOptionPane.showMessageDialog(null, "Para poder realizar una salida debes de indicar una cantidad", "Advertencia", JOptionPane.ERROR_MESSAGE);  
            }
        }else{
            JOptionPane.showMessageDialog(null, "Para poder realizar una salida debes de asignar un producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnConfNuevaActionPerformed

    private void BtnBuscarProdNuevaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarProdNuevaSalidaActionPerformed
        
        BuscarProducto BP = new BuscarProducto();
        BP.setVisible(true);
        BP.toFront();
        BP.requestFocusInWindow();
        
        BP.Frame = 1;
        
    }//GEN-LAST:event_BtnBuscarProdNuevaSalidaActionPerformed
    
    public void limpDat() {    
        txtCantNueva.setText("");
        txtIDNuevaSalida.setText("");
        txtProdNueva.setText("");
    }
    
    public void ConsDatosSalida() {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        modelo.addColumn("ID");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Hora");

        TablaG.TbBusqueda.setModel(modelo);
        TablaG.TbBusqueda.setFocusable(true);
        TablaG.TbBusqueda.setRowSelectionAllowed(true);

        String sql;
        ResultSet rs;
        String[] datos = new String[4];
               
        try {
            
            sql = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Fecha = ? and Salida.Usuario = ? ;";
            
            PreparedStatement pst = cn.prepareStatement(sql);
            
            pst.setString(1, CyA.GlobFecha);
            pst.setString(2, Principal.Nombre);
            
            rs = pst.executeQuery();

            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                double valorCant = Double.parseDouble(rs.getString(3));
                System.out.println(valorCant);
                DecimalFormat df = new DecimalFormat("0.000");
                datos[2] = df.format(valorCant) + " Kg";
                datos[3] = rs.getString(4);
                
                
                modelo.addRow(datos);
            }
            TablaG.TbBusqueda.setModel(modelo);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(NuevaC.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        Principal.ajustarAnchoColumnas(TablaG.TbBusqueda);
        Principal.centrarColumnas(TablaG.TbBusqueda);
        
        TableColumn primeraCol = TablaG.TbBusqueda.getColumnModel().getColumn(0);
        primeraCol.setHeaderRenderer(new FormHeaderCenter()); 
        
        TableColumn SegCol = TablaG.TbBusqueda.getColumnModel().getColumn(1);
        SegCol.setHeaderRenderer(new FormHeaderLeft());
        
        TableColumn terceraCol = TablaG.TbBusqueda.getColumnModel().getColumn(2);
        terceraCol.setHeaderRenderer(new FormHeaderCenter());
        
        TableColumn cuartaCol = TablaG.TbBusqueda.getColumnModel().getColumn(3);
        cuartaCol.setHeaderRenderer(new FormHeaderCenter());
    }

public boolean esDouble(String str) {
    if (str == null || str.isEmpty()) {
        return false; // Una cadena nula o vacía no es un double
    }
    try {
        Double.parseDouble(str);
        return true; // Si la conversión es exitosa, la cadena es un double
    } catch (NumberFormatException e) {
        return false; // Si ocurre una excepción, la cadena no es un double
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarProdNuevaSalida;
    private javax.swing.JButton BtnConfNueva;
    public static javax.swing.JLabel LBIconHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField txtCantNueva;
    public static javax.swing.JTextField txtIDNuevaSalida;
    public static javax.swing.JTextField txtProdNueva;
    // End of variables declaration//GEN-END:variables
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
}
