
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author osmar
 */
public class SalidasPAdmin extends javax.swing.JPanel {

    Carga_y_Asignacion CyA = new Carga_y_Asignacion();
    public String BaseP = Conexion.Base;
    
    public static String formattedDate = "";
    
    public String PP1 = "";
    public String PP2 = "";
    public String PP3 = "";
    public String PP4 = "";   
    public static int TCP = 0;
    
    TablaG Tb = new TablaG();
    
    public SalidasPAdmin() {
        
        initComponents();
           
        
        MostrarT(Tb);
        
        JTextField dateTextField = (JTextField) CalendarModSal.getDateEditor().getUiComponent();
        dateTextField.setEnabled(false);
        dateTextField.setBackground(new java.awt.Color(240,240,240));
        dateTextField.setForeground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        ContenidoSalAdmin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProdSalP = new javax.swing.JTextField();
        txtFechSalP = new javax.swing.JTextField();
        txtCantSalP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adfas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTurnSalP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIDSalP = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CheckProd = new javax.swing.JCheckBox();
        CheckFecha = new javax.swing.JCheckBox();
        CheckTurn = new javax.swing.JCheckBox();
        CheckCant = new javax.swing.JCheckBox();
        txtFiltProdModF = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        CmbUser = new javax.swing.JComboBox<>();
        CalendarModSal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("M E N U   S A L I D A S");

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "TABLA DE SALIDAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 102, 0));

        ContenidoSalAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoSalAdminLayout = new javax.swing.GroupLayout(ContenidoSalAdmin);
        ContenidoSalAdmin.setLayout(ContenidoSalAdminLayout);
        ContenidoSalAdminLayout.setHorizontalGroup(
            ContenidoSalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenidoSalAdminLayout.setVerticalGroup(
            ContenidoSalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Motivo de Salida:");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextPane1.setEnabled(false);
        jTextPane1.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(ContenidoSalAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContenidoSalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "ELIMINAR SALIDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Producto:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cantidad:");

        txtProdSalP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProdSalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFechSalP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechSalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCantSalP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantSalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Hora:");

        adfas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adfas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adfas.setText("asdasd");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Turno:");

        txtTurnSalP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTurnSalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ID de la Salida:");

        txtIDSalP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDSalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdSalP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechSalP, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txtCantSalP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adfas, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtTurnSalP)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDSalP)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIDSalP)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProdSalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adfas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtFechSalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtCantSalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTurnSalP)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true), "FILTRO SALIDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N

        CheckProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckProd.setForeground(new java.awt.Color(255, 102, 0));
        CheckProd.setText("PRODUCTO");
        CheckProd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckProd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckProdMouseClicked(evt);
            }
        });

        CheckFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckFecha.setForeground(new java.awt.Color(255, 102, 0));
        CheckFecha.setText("FECHA");
        CheckFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckFecha.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckFechaMouseClicked(evt);
            }
        });

        CheckTurn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckTurn.setForeground(new java.awt.Color(255, 102, 0));
        CheckTurn.setText("TURNO");
        CheckTurn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckTurn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckTurnMouseClicked(evt);
            }
        });
        CheckTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTurnActionPerformed(evt);
            }
        });

        CheckCant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckCant.setForeground(new java.awt.Color(255, 102, 0));
        CheckCant.setText("CANTIDAD");
        CheckCant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckCant.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckCant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckCantMouseClicked(evt);
            }
        });

        txtFiltProdModF.setEditable(false);
        txtFiltProdModF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFiltProdModF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFiltProdModF.setText("Buscar");
        txtFiltProdModF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        txtFiltProdModF.setEnabled(false);
        txtFiltProdModF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltProdModFMouseClicked(evt);
            }
        });
        txtFiltProdModF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltProdModFActionPerformed(evt);
            }
        });

        txtCant.setEditable(false);
        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCant.setForeground(new java.awt.Color(204, 204, 204));
        txtCant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCant.setText("Especificar");
        txtCant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        txtCant.setEnabled(false);
        txtCant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantMouseClicked(evt);
            }
        });

        CmbUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CmbUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        CmbUser.setEnabled(false);
        CmbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbUserMouseClicked(evt);
            }
        });

        CalendarModSal.setBackground(new java.awt.Color(255, 255, 255));
        CalendarModSal.setDateFormatString("dd/MM/yyyy");
        CalendarModSal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CalendarModSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarModSalMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("FILTRAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CheckTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckCant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCant, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiltProdModF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmbUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CalendarModSal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltProdModF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(CalendarModSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckProdMouseClicked

        if (CheckProd.isSelected() == true){
            txtFiltProdModF.setText("");
            txtFiltProdModF.setBackground(Color.WHITE);
            txtFiltProdModF.setForeground(new java.awt.Color(0,0,0));

            BuscarProducto BP = new BuscarProducto();
            BP.setVisible(true);
            BP.Frame = 3;
        }else{
            txtFiltProdModF.setText("Buscar");
            txtFiltProdModF.setBackground(new java.awt.Color(240,240,240));
        }

    }//GEN-LAST:event_CheckProdMouseClicked

    private void CheckFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckFechaMouseClicked

        JTextField dateTextField = (JTextField) CalendarModSal.getDateEditor().getUiComponent();

        LocalDate now = LocalDate.now();

        DateTimeFormatter formOneM = DateTimeFormatter.ofPattern("MM/dd/yyyy");

        Date d = new Date(now.format(formOneM));

        System.out.println(d);

        if (CheckFecha.isSelected() == true){
            dateTextField.setBackground(new java.awt.Color(255,255,255));
            dateTextField.setForeground(new java.awt.Color(0,0,0));
            CalendarModSal.setDate(d);
        }else{
            dateTextField.setBackground(new java.awt.Color(240,240,240));
            dateTextField.setForeground(new java.awt.Color(255,255,255));
            dateTextField.setText("");
        }

    }//GEN-LAST:event_CheckFechaMouseClicked

    private void CheckTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckTurnMouseClicked

        if (CheckTurn.isSelected() == true){
            CmbUser.setEnabled(true);
            CmbUser.setSelectedIndex(0);
        }else{
            CmbUser.setEnabled(false);
            CmbUser.setSelectedIndex(-1);
        }

    }//GEN-LAST:event_CheckTurnMouseClicked

    private void CheckTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTurnActionPerformed

    }//GEN-LAST:event_CheckTurnActionPerformed

    private void CheckCantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckCantMouseClicked

        if (CheckCant.isSelected() == true){
            txtCant.setText("");
            txtCant.setBackground(Color.WHITE);
            txtCant.setForeground(new java.awt.Color(0,0,0));
            txtCant.setEnabled(true);
            txtCant.setEditable(true);
        }else{
            txtCant.setText("Especificar");
            txtCant.setBackground(new java.awt.Color(240,240,240));
            txtCant.setForeground(new java.awt.Color(140,140,140));

        }

    }//GEN-LAST:event_CheckCantMouseClicked

    private void txtFiltProdModFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltProdModFMouseClicked

        CheckProd.setSelected(true);

        txtFiltProdModF.setText("");
        txtFiltProdModF.setBackground(Color.WHITE);
        txtFiltProdModF.setForeground(new java.awt.Color(0,0,0));

        BuscarProducto BP = new BuscarProducto();
        BP.setVisible(true);
        BP.Frame = 3;
    }//GEN-LAST:event_txtFiltProdModFMouseClicked

    private void txtFiltProdModFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltProdModFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltProdModFActionPerformed

    private void txtCantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantMouseClicked

        CheckCant.setSelected(true);

        txtCant.setEditable(true);
        txtCant.setEnabled(true);
        txtCant.setText("");
        txtCant.setBackground(Color.WHITE);
        txtCant.setForeground(new java.awt.Color(0,0,0));

    }//GEN-LAST:event_txtCantMouseClicked

    private void CmbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbUserMouseClicked

        CheckTurn.setSelected(true);
        CmbUser.setEnabled(true);
        CmbUser.setSelectedIndex(0);

    }//GEN-LAST:event_CmbUserMouseClicked

    private void CalendarModSalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalendarModSalMouseClicked

    }//GEN-LAST:event_CalendarModSalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!txtFiltProdModF.getText().equals("")){
            if (!txtCant.getText().equals("")){
                if (CmbUser.getSelectedIndex() != -1){
                    LlamarFecha();
                    ConsDatosSalidaP();
                }else{
                    if (CheckTurn.isSelected() == true){
                        JOptionPane.showMessageDialog(null, "Favor de SELECCIONAR un USUARIO o DESACTIVAR el filtro", "Advertencia", JOptionPane.ERROR_MESSAGE);
                    }else{
                        LlamarFecha();
                        ConsDatosSalidaP();
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Favor de INDICAR una CANTIDAD o DESACTIVAR el filtro", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Favor de SELECCIONAR un PRODUCTO o DESACTIVAR el filtro", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MostrarT(JPanel F){        
        F.setSize(781, 356);
        F.setLocation(2, 0);
        
        ContenidoSalAdmin.add(F, BorderLayout.CENTER);
        ContenidoSalAdmin.revalidate();
        ContenidoSalAdmin.repaint();        
    }
    
    public void LlamarFecha() {
    Date selectedDate = CalendarModSal.getDate();   
        
        if (selectedDate != null) {
           SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
           formattedDate = dateFormat.format(selectedDate);
           System.out.println("Fecha seleccionada: " + formattedDate); 
        }else{
            System.out.println("No se selecciono fecha");
        }
}
    
    public void ConsDatosSalidaP() {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        modelo.addColumn("ID");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Hora");
        modelo.addColumn("Fecha");

        TablaG.TbBusqueda.setModel(modelo);
        TablaG.TbBusqueda.setFocusable(true);
        TablaG.TbBusqueda.setRowSelectionAllowed(true);
        
        //Reinicio de Variables Globales (PP1 - PP2 - PP3 - PP4)
        PP1 = "";
        PP2 = "";
        PP3 = "";
        PP4 = "";
        TCP = 0;
        
        System.out.println(PP1);
        System.out.println(PP2);
        System.out.println(PP3);
        System.out.println(PP4);
        System.out.println(TCP);

        String sql;
        ResultSet rs;
        Statement st;

        String Fecha = CyA.GlobFecha;
        String Usuario = Principal.Nombre;
        String Base = ""; 
        
        String[] datos = new String[4];
        
        if (CheckFecha.isSelected() == true && CheckTurn.isSelected() == true){
            Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where ";
        }else{
            if (CheckFecha.isSelected() == true){
                TCP++;
                Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Usuario = '" + Usuario + "'";
            }else{
                if (CheckTurn.isSelected() == true){
                    TCP++;
                    Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Fecha = '" + Fecha + "'";
                }else{
                    TCP++;
                   Base = "select idSalida, Producto, Cantidad, Hora from " + BaseP + ".Salida where Salida.Usuario = '" + Usuario + "' and Salida.Fecha = '" + Fecha + "'"; 
                }
            }
        }
                   
        //if que me comprueba el estado del check PRODUCTO
        if (TCP >= 1){
            if (CheckProd.isSelected() == true){
                PP1 = " and Salida.Producto = '" + txtFiltProdModF.getText() + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Producto");
            }
        }else{
            if (CheckProd.isSelected() == true){
                PP1 = "Salida.Producto = '" + txtFiltProdModF.getText() + "'";
                TCP++;
            }else{
                PP1 = "";
                System.out.println("No se selecciono el filtro de Producto");
            }
        }
        
        //if que me comprueba el estado del check FECHA
        if (TCP >= 1){
            if (CheckFecha.isSelected() == true){
                PP2 = " and Salida.Fecha = '" + formattedDate + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Fecha");
            }
        }else{
            if (CheckFecha.isSelected() == true){
                PP2 = "Salida.Fecha = '" + formattedDate + "'";
                TCP++;
            }else{
                PP2 = "";
                System.out.println("No se selecciono el filtro de Fecha");
            }
        }
        
        //if que me comprueba el estado del check CANTIDAD
        if (TCP >= 1){
            if (CheckCant.isSelected() == true){
                PP3 = " and Salida.Cantidad = '" + txtCant.getText() + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Cantidad");
            }
        }else{
            if (CheckCant.isSelected() == true){
                PP3 = "Salida.Cantidad = '" + txtCant.getText() + "'";
                TCP++;
            }else{
                PP3 = "";
                System.out.println("No se selecciono el filtro de Cantidad");
            }
        }
        
        //if que me comrueba el estado del check TURNO
        if (TCP >= 1){
            if (CheckTurn.isSelected() == true){
                PP4 = " and Salida.Usuario = '" + CmbUser.getSelectedItem().toString() + "'";
                TCP++;
            }else{
                System.out.println("No se selecciono el filtro de Turno");
            }
        }else{
            if (CheckTurn.isSelected() == true){
                PP4 = "Salida.Usuario = '" + CmbUser.getSelectedItem().toString() + "'";
                TCP++;
            }else{
                PP4 = "";
                System.out.println("No se selecciono el filtro de Turno");
            }
        }
        
        sql = Base + PP1 + PP2 + PP3 + PP4 + ";";
        System.out.println(sql);
        
        try {
            
            st = cn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                double valorCant = Double.parseDouble(rs.getString(3));
                System.out.println(valorCant);
                DecimalFormat df = new DecimalFormat("0.000");
                datos[2] = df.format(valorCant) + " Kg";
                datos[3] = rs.getString(4);
                
                
                modelo.addRow(datos);
            }
            TablaG.TbBusqueda.setModel(modelo);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(NuevaC.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        Principal.ajustarAnchoColumnas(TablaG.TbBusqueda);
        Principal.centrarColumnas(TablaG.TbBusqueda);
        
        TableColumn primeraCol = TablaG.TbBusqueda.getColumnModel().getColumn(0);
        primeraCol.setHeaderRenderer(new FormHeaderCenter()); 
        
        TableColumn SegCol = TablaG.TbBusqueda.getColumnModel().getColumn(1);
        SegCol.setHeaderRenderer(new FormHeaderLeft());
        
        TableColumn terceraCol = TablaG.TbBusqueda.getColumnModel().getColumn(2);
        terceraCol.setHeaderRenderer(new FormHeaderCenter());
        
        TableColumn cuartaCol = TablaG.TbBusqueda.getColumnModel().getColumn(3);
        cuartaCol.setHeaderRenderer(new FormHeaderCenter());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser CalendarModSal;
    private javax.swing.JCheckBox CheckCant;
    private javax.swing.JCheckBox CheckFecha;
    private javax.swing.JCheckBox CheckProd;
    private javax.swing.JCheckBox CheckTurn;
    public static javax.swing.JComboBox<String> CmbUser;
    private javax.swing.JPanel ContenidoSalAdmin;
    public static javax.swing.JTextField adfas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    public static javax.swing.JTextField txtCant;
    public static javax.swing.JTextField txtCantSalP;
    public static javax.swing.JTextField txtFechSalP;
    public static javax.swing.JTextField txtFiltProdModF;
    public static javax.swing.JTextField txtIDSalP;
    public static javax.swing.JTextField txtProdSalP;
    public static javax.swing.JTextField txtTurnSalP;
    // End of variables declaration//GEN-END:variables
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
}
